apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: abhinandan1311/devcode-backend
          ports:
            - containerPort: 8181
          env:
          - name: PSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: backend-secret
                key: PSQL_PASSWORD
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: backend-secret
                key: JWT_SECRET
          - name: LINODE_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: backend-secret
                key: LINODE_ACCESS_KEY_ID
          - name: LINODE_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: backend-secret
                key: LINODE_SECRET_ACCESS_KEY
          - name: PSQL_HOST
            valueFrom:
              secretKeyRef:
                name: backend-secret
                key: PSQL_HOST
          - name: PSQL_USER
            valueFrom:
              secretKeyRef:
                name: backend-secret
                key: PSQL_USER
          - name: PSQL_DB
            valueFrom:
              secretKeyRef:
                name: backend-secret
                key: PSQL_DB
          - name: PSQL_PORT
            valueFrom:
              secretKeyRef:
                name: backend-secret
                key: PSQL_PORT    